# Warning: only edit this file inside the images git repository.
# If you are looking at this file in your root directory on your computer, editing it does nothing.

# The image will be at ghcr.io/yourusername/name
name: riced

# The native container image to build on top of
# Warning: Non-uBlue images might function unexpectly
base-image: ghcr.io/hyprblue/gaming

# What fedora version to use. Use an explicit version or `latest`.
# If you use `latest`, you will be automatically updated
# to the next major version assuming the image you're using as your base container
# builds with the tag (all uBlue images do this).
fedora-version: latest

# This description will be visible in the container metadata
description: My personal riced image based on hyprblue/gaming.

# These scripts will be executed during the container build
# Place scripts in scripts/ and put the corresponding filename here
scripts:
  - insync.sh

# The scripts will be executed after packages are installed
# An example use case it to enable services
# Place these scripts in post-install/ and put the corresponding filename here
post-install:
# - example.sh

# a list of urls of .repo files that should be added to your system
# this is the proper way to add copr repos to your image
extrarepos:
# - example.repo

# These packages will be removed before the installing packages
remove:
  - thunar
  - htop

# These rpms will be installed from the fedora repository
# using rpm-ostree and will be preinstalled in the final image
rpms:
  - nautilus
  - insync
  - btop

# These Flatpaks (from flathub) will be available for install on boot
# If you leave this empty you can use yafti for post-boot installation
flatpaks:
  - com.getmailspring.Mailspring
  - com.github.GradienceTeam.Gradience
  - com.github.wwmm.easyeffects
  - com.microsoft.Edge
  - com.spotify.Client
  - io.github.celluloid_player.Celluloid
  - md.obsidian.Obsidian
  - org.bionus.Grabber
  - org.openrgb.OpenRGB
